apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ostry7/terraform.git
    targetRevision: HEAD
    path: gitops/helm/gitops-helmchart
    helm:
      valueFiles:
        - environment/prod/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true