apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ostry7/terraform.git
    targetRevision: HEAD
    path: GitOps-Based Kubernetes Platform on Azure/gitops/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true     #ArgoCD delete unused resources
      selfHeal: true  #ArgoCD Restores the cluster to the state it was in the repository if someone manually changes something on the cluster