apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cluster
  namespace: prod
spec:
  instances: 1
  bootstrap:
    initdb:
      database: devops_db
      owner: app
      postInitSQL:
        - |
          CREATE TABLE IF NOT EXISTS users (
            id    SERIAL PRIMARY KEY,
            name  VARCHAR(100) NOT NULL,
            email VARCHAR(150) NOT NULL,
            role  VARCHAR(50)  DEFAULT 'user'
          );
          CREATE TABLE IF NOT EXISTS products (
            id       SERIAL PRIMARY KEY,
            name     VARCHAR(100) NOT NULL,
            price    NUMERIC(10,2) NOT NULL,
            category VARCHAR(80) DEFAULT 'general'
          );
        - |
          INSERT INTO users (name, email, role) VALUES
            ('Jan Kowalski', 'jan@example.com', 'admin'),
            ('Anna Nowak', 'anna@example.com', 'user');
        - |
          INSERT INTO products (name, price, category) VALUES
            ('Laptop', 3999.99, 'electronics'),
            ('Klawiatura', 199.99, 'accessories');
  storage:
    size: 1Gi