apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: psql-db
  namespace: prod
spec:
  selector:
    matchLabels:
      app: psql-db
  serviceName: psql-db-headless
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: psql-db
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: postgres
        image: postgres:16
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: psql-secret
              key: db_password
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: psql-configmap
              key:  postgres_user
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: psql-configmap
              key: postgres_db
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        - name: sql
          mountPath: /sql
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB" -h 127.0.0.1 -p 5432
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB" -h 127.0.0.1 -p 5432
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
  volumes:
  - name: sql
    configMap:
      name: psql-configmap