apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cluster-dr
  namespace: prod
spec:
  instances: 1

  bootstrap:
    recovery:
      source: cnpg-cluster-primary

  replica:
    enabled: true
    source: cnpg-cluster-primary

  externalClusters:
    - name: cnpg-cluster-primary
      connectionParameters:
        host: "10.240.0.62"
        port: "5432"
        user: streaming_replica
        dbname: postgres
        sslmode: verify-ca
      sslCert:
        name: cnpg-cluster-primary-replication
        key: tls.crt
      sslKey:
        name: cnpg-cluster-primary-replication
        key: tls.key
      sslRootCert:
        name: cnpg-cluster-primary-ca
        key: ca.crt
      barmanObjectStore:
        destinationPath: "<storage_account_path>"
        azureCredentials:
          inheritFromAzureAD: true
        wal:
          compression: gzip

  storage:
    size: 1Gi