apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
  namespace: dev
  labels:
    app: devops-app
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
        env: dev
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: devops-app
          image: gitopscontainerregistry7677.azurecr.io/devops-app:36ff42e188bad529799c8166e2b0fedde25d70d5
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi