apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.app_name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.app_name }}
    env: {{ .Values.global.environment }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.global.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.app_name }}
        env: {{ .Values.global.environment }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: {{ .Values.global.app_name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          env:
            - name: ENV
              value: {{ .Values.global.environment }}
            - name: DB_HOST #CNPG service (read-write)
              value: {{ .Values.global.db_host }}
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "devops_db" #db from bootstrap CNPG cluster
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cnpg-cluster-primary-app 
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cnpg-cluster-primary-app 
                  key: password
            - name: DB_MODE
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: db_mode
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi