name: ci_prepare_azure_env.yaml
on:
  workflow_dispatch:
  push:
    branches:
      - features
    paths: 
      - 'Azure AKS Deployment Pipeline/terraform/**'  #runs only if any changes on terraform dir

env:
  TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  terraform_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        working-directory: "Azure AKS Deployment Pipeline/terraform/"
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        working-directory: "Azure AKS Deployment Pipeline/terraform/"
        run: |
          terraform init -backend=false
          terraform validate
          
  create_azure_env:
    needs: terraform_lint 
    if: needs.terraform_lint.result == 'success' #runs only if terraform lint completed successfuly
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        working-directory: "Azure AKS Deployment Pipeline/terraform/"
        run: terraform init

      - name: Terraform Plan
        working-directory: "Azure AKS Deployment Pipeline/terraform/"
        run: terraform plan

      - name: Terraform Apply
        working-directory: "Azure AKS Deployment Pipeline/terraform/"
        run: terraform apply -auto-approve

  acr_push:
    needs: create_azure_env 
    if: needs.create_azure_env.result == 'success' #runs only if create_acure_env completed successfuly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Enable ACR Admin
        run: az acr update -n acrapp01 --admin-enabled true

      - name: Start Docker daemon
        run: |
          sudo dockerd &
          sleep 15
          sudo docker info

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ACR
        uses: docker/login-action@v3
        with:
          registry: acrapp01.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push to ACR
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: acrapp01.azurecr.io/devops-app:latest
          file: Azure AKS Deployment Pipeline/app/Dockerfile
          context: Azure AKS Deployment Pipeline/app/
      
      - name: Get AKS credentials #give AKS priviledge to get image from ACR
        run: |
          az aks get-credentials \
            --resource-group infra_rg_123456 \
            --name example-aks1-test123
            
      - name: Deploy to AKS
        run: |
          kubectl apply -f "Azure AKS Deployment Pipeline/Kubernetes/deployment.yaml"
          kubectl apply -f "Azure AKS Deployment Pipeline/Kubernetes/service.yaml"
          kubectl rollout restart deployment devops-app
          kubectl rollout status deployment devops-app