# pipeline runs when terraform code changed
name: Project2_ci_infrastructure.yaml
on:
  workflow_dispatch: 
  push: 
    paths:
      - 'GitOps-Based Kubernetes Platform on Azure/terraform/**'

env:
  TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  terraform_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        working-directory: "GitOps-Based Kubernetes Platform on Azure/terraform/"
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        working-directory: "GitOps-Based Kubernetes Platform on Azure/terraform/"
        run: |
          terraform init -backend=false
          terraform validate

  create_azure_env:
    needs: terraform_lint 
    if: needs.terraform_lint.result == 'success' #runs only if terraform lint completed successfuly
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        working-directory: "GitOps-Based Kubernetes Platform on Azure/terraform/"
        run: terraform init

      - name: Terraform Plan
        working-directory: "GitOps-Based Kubernetes Platform on Azure/terraform/"
        run: terraform plan

      - name: Terraform Apply
        working-directory: "GitOps-Based Kubernetes Platform on Azure/terraform/"
        run: terraform apply -auto-approve

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
      
      - name: Get AKS credentials
        run: |
          az aks get-credentials \
            --resource-group gitops_rg2345234 \
            --name example-aks1_test234
    
      - name: Create Kubernetes Namespaces
        run:  |
          kubectl create namespace stage --dry-run=client -o yaml | kubectl apply -f -
          kubectl create namespace prod --dry-run=client -o yaml | kubectl apply -f -