# pipeline deploy image tag once approval is clicked
name: Project2_cd_prod_deploy.yaml
on:
  workflow_run: 
    workflows: "Project2_ci_build.yaml"
    types:
      - completed

jobs:
  promote-prod:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update prod manifest
        run: |
          IMAGE_TAG=${{ github.event.workflow_run.head_sha }}

          sed -i "s|tag:.*|tag: ${IMAGE_TAG}|" \
            "GitOps-Based Kubernetes Platform on Azure/gitops/helm/gitops-helmchart/environment/prod/values.yaml"
      
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
      
          git add "GitOps-Based Kubernetes Platform on Azure/gitops/helm/gitops-helmchart/environment/prod/values.yaml"
          git commit -m "Update dev image tag to ${IMAGE_TAG}"
          git push

      