# pipeline runs when app code changed
name: Project2_ci_build.yaml
on:
  workflow_dispatch: 
  push: 
    paths:
      - 'GitOps-Based Kubernetes Platform on Azure/app/**'

jobs:
  acr_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Start Docker daemon
        run: |
          sudo dockerd &
          sleep 15
          sudo docker info

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ACR
        run: az acr login --name gitopscontainerregistry7677

      - name: Build and Push to ACR
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: gitopscontainerregistry7677.azurecr.io/devops-app:${{ github.sha }}
          file: GitOps-Based Kubernetes Platform on Azure/app/Dockerfile
          context: GitOps-Based Kubernetes Platform on Azure/app/
      
#      - name: Get AKS credentials #give AKS priviledge to get image from ACR
#        run: |
#          az aks get-credentials \
#            --resource-group gitops_rg2345234 \
#            --name example-aks1_test234
#
#      - name: Deploy to AKS
#        run: |
#          kubectl apply -f "GitOps-Based Kubernetes Platform on Azure/Kubernetes/deployment.yaml"
#          kubectl apply -f "GitOps-Based Kubernetes Platform on Azure/Kubernetes/service.yaml"
#          
#          kubectl rollout restart deployment devops-app
#          kubectl rollout status deployment devops-app

      - name: Update image tag in gitops/dev
        run:  |
          IMAGE_TAG=${{ github.sha }}
          sed -i "s|gitopscontainerregistry7677.azurecr.io/devops-app:.*|gitopscontainerregistry7677.azurecr.io/devops-app:${IMAGE_TAG}|" \
            "GitOps-Based Kubernetes Platform on Azure/gitops/dev/deployment.yaml"
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git add "GitOps-Based Kubernetes Platform on Azure/gitops/dev/deployment.yaml"
          git commit -m "Update dev image tag to ${IMAGE_TAG}"
          git push